<option value="Afrique du sud">Afrique du Sud</option>
<option value="Algerie">Algerie</option>
<option value="Allemagne">Allemagne</option>
<option value="Arabie Saoudite">Arabie Saoudite</option>
<option value="Australie">Australie</option>
<option value="Bahamas">Bahamas</option>
<option value="Belgique">Belgique</option>
<option value="Bresil">Bresil</option>
<option value="Cameroun">Cameroun</option>
<option value="Canada">Canada</option>
<option value="Canaries">Canaries</option>
<option value="Chine">Chine</option>
<option value="Croatie">Croatie</option>
<option value="Danemark">Danemark</option>
<option value="Egypte">Egypte</option>
<option value="Espagne">Espagne</option>
<option value="Etats Unis">Etats Unis</option>
<option value="Finlande">Finlande</option>
<option value="France">France</option>
<option value="Ghana">Ghana</option>
<option value="Grece">Grece</option>
<option value="Guinee">Guinee</option>
<option value="Haiti">Haiti</option>
<option value="Irlande">Irlande</option>
<option value="Islande">Islande</option>
<option value="Israel">Israel</option>
<option value="Italie">italie</option>
<option value="Jamaique">Jamaique</option>
<option value="Japon">Japon</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Lybie">Lybie</option>
<option value="Madagascar">Madagascar</option>
<option value="Madère">Madère</option>
<option value="Malaisie">Malaisie</option>
<option value="Malawi">Malawi</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malte">Malte</option>
<option value="Maroc">Maroc</option>
<option value="Martinique">Martinique</option>
<option value="Maurice">Maurice</option>
<option value="Mauritanie">Mauritanie</option>
<option value="Mexique">Mexique</option>
<option value="Monaco">Monaco</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="Norvege">Norvege</option>
<option value="Nouvelle Caledonie">Nouvelle Caledonie</option>
<option value="Nouvelle Zelande">Nouvelle Zelande</option>
<option value="Panama">Panama</option>
<option value="Paraguay">Paraguay</option>
<option value="Pays Bas">Pays Bas</option>
<option value="Perou">Perou</option>
<option value="Pologne">Pologne</option>
<option value="Portugal">Portugal</option>
<option value="Qatar">Qatar</option>
<option value="Republique Dominicaine">Republique Dominicaine</option>
<option value="Republique Tcheque">Republique Tcheque</option>
<option value="Reunion">Reunion</option>
<option value="Royaume Uni">Royaume Uni</option>
<option value="Russie">Russie</option>
<option value="Senegal">Senegal</option>
<option value="Singapour">Singapour</option>
<option value="Slovaquie">Slovaquie</option>
<option value="Slovenie">Slovenie</option>
<option value="Soudan">Soudan</option>
<option value="Suede">Suede</option>
<option value="Suisse">Suisse</option>
<option value="Thailande">Thailande</option>
<option value="Togo">Togo</option>
<option value="Tunisie">Tunisie</option>
<option value="Turquie">Turquie</option>
<option value="Ukraine">Ukraine</option>
<option value="Uruguay">Uruguay</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietnam">Vietnam</option>