<option value="Aéroport international d'Alger - Houari Boumédiène">Aéroport international d'Alger - Houari Boumédiène</option>
<option value="Aéroport de Paris-Orly">Aéroport de Paris-Orly</option>
<option value="Aéroport de Paris-Charles De Gaulle">Aéroport de Paris-Charles De Gaulle</option>
<option value="Aéroport Marseille Provence">Aéroport Marseille Provence</option>
<option value="International Airport of Tunis-Carthage">International Airport of Tunis-Carthage</option>
<option value="Aéroport d'Istanbul">Aéroport d'Istanbul</option>
<option value="Aéroport international de Dubaï">Aéroport international de Dubaï</option>
<option value="Aéroport international Pierre-Elliott-Trudeau de Montréal">Aéroport international Pierre-Elliott-Trudeau de Montréal</option>
<option value="Aéroport International Mohammed V">Aéroport International Mohammed V</option>
<option value="Aéroport de Londres Heathrow">Aéroport de Londres Heathrow</option>
<option value="Aéroport Léonard-de-Vinci de Rome Fiumicino">Aéroport Léonard-de-Vinci de Rome Fiumicino</option>
<option value="Aéroport de Kiev Boryspil">Aéroport de Kiev Boryspil</option>
<option value="Aéroport international John F. Kennedy">Aéroport international John F. Kennedy</option>
<option value="Aéroport international OR Tambo">Aéroport international OR Tambo</option>
<option value="Aéroport de Moscou-Domodedovo">Aéroport de Moscou-Domodedovo</option>
<option value="Aéroport d'Adrar - Touat - Cheikh Sidi Mohamed Belkebir">Aéroport d'Adrar - Touat - Cheikh Sidi Mohamed Belkebir</option>
<option value="Aéroport d'Annaba - Rabah-Bitat">Aéroport d'Annaba - Rabah-Bitat</option>
<option value="Aéroport de Batna - Mostepha Ben Boulaid">Aéroport de Batna - Mostepha Ben Boulaid</option>
<option value="Aéroport de Béchar - Boudghene Ben Ali Lotfi">Aéroport de Béchar - Boudghene Ben Ali Lotfi</option>
<option value="Aéroport de Béjaïa - Soummam - Abane Ramdane">Aéroport de Béjaïa - Soummam - Abane Ramdane</option>
<option value="Aéroport de Biskra - Mohamed Khider">Aéroport de Biskra - Mohamed Khider</option>
<option value="Aéroport de Bordj Mokhtar">Aéroport de Bordj Mokhtar</option>
<option value="Aéroport de Bou Saâda">Aéroport de Bou Saâda</option>
<option value="Aéroport de Chlef">Aéroport de Chlef</option>
<option value="Aéroport de Constantine - Mohamed Boudiaf">Aéroport de Constantine - Mohamed Boudiaf</option>
<option value="Aéroport de Djanet - Tiska">Aéroport de Djanet - Tiska</option>
<option value="Aéroport de Djanet - Tiska">Aéroport d'El Bayadh</option>
<option value="Aéroport d'El Goléa">Aéroport d'El Goléa</option>
<option value="Aéroport d'El Oued - Guemar">Aéroport d'El Oued - Guemar</option>
<option value="Aéroport de Ghardaïa - Noumérat - Moufdi Zakaria">Aéroport de Ghardaïa - Noumérat - Moufdi Zakaria</option>
<option value="Aéroport de Ghriss">Aéroport de Ghriss</option>
<option value="Aéroport d'Hassi Messaoud - Oued Irara - Krim Belkacem">Aéroport d'Hassi Messaoud - Oued Irara - Krim Belkacem</option>
<option value="Aéroport d'Hassi R'Mel - Tilrhemt">Aéroport d'Hassi R'Mel - Tilrhemt</option>
<option value="Aéroport d'Illizi - Takhamalt">Aéroport d'Illizi - Takhamalt</option>
<option value="Aéroport d'In Guezzam">Aéroport d'In Guezzam</option>
<option value="Aéroport d'In Salah">Aéroport d'In Salah</option>
<option value="Aéroport de Jijel - Ferhat Abbas">Aéroport de Jijel - Ferhat Abbas</option>
<option value="Aéroport de Laghouat - Moulay Ahmed Medeghri">Aéroport de Laghouat - Moulay Ahmed Medeghri</option>
<option value="Aéroport de Méchria">Aéroport de Méchria</option>
<option value="Aéroport d'Oran - Ahmed Ben Bella">Aéroport d'Oran - Ahmed Ben Bella</option>
<option value="Aéroport d'Ouargla - Aïn Beida">Aéroport d'Ouargla - Aïn Beida</option>
<option value="Aéroport de Sétif - 8 Mai 1945">Aéroport de Sétif - 8 Mai 1945</option>
<option value="Aéroport de Tamanrasset - Aguenar - Hadj Bey Akhamok">Aéroport de Tamanrasset - Aguenar - Hadj Bey Akhamok</option>
<option value="Aéroport de Tébessa - Cheikh Larbi Tébessi">Aéroport de Tébessa - Cheikh Larbi Tébessi</option>
<option value="Aéroport de Tiaret - Abdelhafid Boussouf Bou Chekif">Aéroport de Tiaret - Abdelhafid Boussouf Bou Chekif</option>
<option value="Aéroport de Timimoun">Aéroport de Timimoun</option>
<option value="Aéroport de Tindouf">Aéroport de Tindouf</option>
<option value="Aéroport de Tlemcen - Zenata - Messali El Hadj">Aéroport de Tlemcen - Zenata - Messali El Hadj</option>
<option value="Aéroport de Touggourt - Sidi Mahdi">Aéroport de Touggourt - Sidi Mahdi</option>
<option value="Aéroport de Zarzaïtine - In Amenas">Aéroport de Zarzaïtine - In Amenas</option>